name: on_call_work
description: Connect people for an on-call work

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  latlong2: ^0.8.1
  dart_geohash: ^2.0.2
  flutter_map: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
